{% set name = "pygaps" %}
{% set version = "4.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygaps-{{ version }}.tar.gz
  sha256: c31e3a52e8cd23a3f10152d19a2675945964fc9bce29256a156894700a8e1eaf

build:
  noarch: python
  entry_points:
    - pygaps = pygaps.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - importlib-resources
    - numpy >=1.16.5
    - pandas >=1.1
    - scipy >=1.6
    - matplotlib-base >=3.0
    - coolprop >=6.0
    - adsorption-file-parser >=0.1.7
    - xlrd >=1.1
    - xlwt >=1.3
    - openpyxl
    - gemmi
    - requests

test:
  imports:
    - pygaps
  commands:
    - pip check
    - pygaps --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pauliacomi/pygaps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A framework for processing adsorption data for porous materials
  doc_url: https://pygaps.readthedocs.io
  dev_url: https://github.com/pauliacomi/pygaps

extra:
  recipe-maintainers:
    - pauliacomi
